/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonar_cube.app;

import sonar_cube.list.LinkedList;

import static sonar_cube.utilities.StringUtils.join;
import static sonar_cube.utilities.StringUtils.split;
import static sonar_cube.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        int a = 7;
        System.out.println("Hello World");
    }
}
