/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonar_cube.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
    	MessageUtils mu = new MessageUtils();
        assertEquals("Hello      World!", mu.getMessage());
    }
}
